CHROMA_API_KEY = "ck-9RQ95N7dH1FcFpKPfXzm5seZNbW3j7ibBZQWSHcSqWg"
CHROMA_TENANT = "429054f3-d864-4a24-8abd-4a0ce5b88f11"
CHROMA_DATABASE = "esclation"
# The name of your Google Sheet for logging escalations
GSHEET_NAME = "escalations"

# Google Sheets Credentials
# Copy and paste the entire content of the JSON file you downloaded from Google Cloud here
[gcp_service_account]
type = "service_account"
project_id = "crm-472718"
private_key_id = "76baacffd832f905dea3a1824ba579ea2e518e6f"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQCxS9vL+c7SGy7Q\nUm3EK8UF8oBCEVSBznPzq1+8sgP3WaoN/9uJN2CLEMteD/7Q7HwGMIT1rNcf0Chx\nQ6RiknS+4Rwvd7R1/55PD44zKhv1DjQQqV4iTngEPZq8nb+ij4T6BHtNxk9a6Vye\n8tioj4yousD1ZrFqBCUuLSnVEhyID4ttTr2WjBAJM01eAbNM46Omi5SlORApeKMN\n2p9lXr99Nzc3YyyLLkoQuAcX5o0nDI0Hh1qlPgzUve8Nnrd1h6DYjesfOemnpEdw\nZufYbxq7kWQGXj5ppAoQPYMoEp9+/FIEwqic6IeavV5PZ0ov81lRZJ374/AKQ6zV\nVTCVYEcZAgMBAAECggEAN6CgAXNLL4QE36sFMqgzBKcuE8yhMasnmVv7SVanROv2\nnbbZ2EcuPOPTkxs8rauNTFnb1cNZqesjTUpWYPEnvR4fPEt4LQ+7SX4NdUMwi2Zd\n8p5ZYTUylc4IZ0atcmFKbTGLyH7AtjsC6wIx9U046lXSJg0G/Eb5rW/RML+igROs\nNHcOCVEF33cMexsEwbGC0BBc+QWq48ISN/0PjaXsogyP26o4EmUByJD99khnyH+n\nhH2YRPD8YbWQ037JmFFyeQ2q0AL5ASr2qk6T7RRB2kwgGrzWWkAgZgEXFhuvGp4S\n8pMZ214P0Kr0PXG3QlCTsofqwLEbYBA3pKuDwFhRGwKBgQD4xKMfgIYljGyM/akK\n0ixiQi0wfR8MgvaoZp9gernmB9GLBCmjSA2SZqVescyWRts/m8QP/bvtZepJPGvq\nZ51mu3OvDisj0fZKbQ5kXqBee6v3S9/ciDOv4q78wvmgvO3TGj89EFLAwFKCpwbl\n+d6DUkB9kNwbqMX+N26DF6n0CwKBgQC2c1HN5rmzrVaF4pJdaQ1qHu1whVFvlD6J\n4CR2R0iWGvC7fe3ZwVsXsgGYTdHUQQDduBdrESq+6CUbTKZUBy9unVvr9LMat0vS\nx6IdOr8uG+dpZMVeySZEgErXGtS3sMe+EoIFNjizDhl/2pMqZma7GoeENveRvBMr\ny5JGYhdj6wJ/B8YdUt6xUnsQ6VcD8VKgEHIA94LxdXKiQqDyWhF7vbSA19dJddDK\nm8iZYlwsCIYuU86KUfWb6c9FgwRgWvLh+FPjSZUnw/bLu4es63YJjOpQdWnplPqs\notJypXNyWZON2wr27vGTpHJeIbcWgBlO2su3ODVOq46aoVcaHP6gUQKBgDHcNgDl\nCt7Vgg24q3MnoGjd5tmXNXgetTCMtqo0NNwApMU4VuXpd3F0TgdHTQ6KbSgqhQvX\ndy0Q2AMr4VCZXhcGnfZPuxqT+P6zW9RNF64MJiOhTGbo5bJWtR0v0e4ZO5zwBeRS\nuxADzGgqXYl6zpxXVa2GMAX9teeEDId7ixTdAoGAPKsNMZs7ggRkX2KR6S7Bl9Bc\nqfve26BCZB5sBYv7Dt/fI1/6JqKx+fZyF+DSwJOL8+KfBtTapxPMII7bbsTAghK/\nbsUTZ33GayoFRgFkWYn47ROA4gUDkgpn/OdAUVOSuL7g1WSTFhTxmfsqosi+tZ9M\nDWj4Cu1KW8Npmdtn1J0=\n-----END PRIVATE KEY-----\n"
client_email = "crm-esclation@crm-472718.iam.gserviceaccount.com"
client_id = "113570054431665602566"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/crm-esclation%40crm-472718.iam.gserviceaccount.com"

[gcs]
bucket_name = "onyx-escalations"

[google]
api_key = "AIzaSyChJo4kcat8nAUSJ2_ArJwLIn6zfmLAMGI"